### PR TITLE
Fixed hand-e visual invisible in rviz

### PR DESCRIPTION
**Pull request by BobbyCephy**

### CODE REVIEW

**Comment by cambel** [comment]
@BobbyCephy Thank you for the contribution!

Could you explain in more detail what the problem was and what you changed to fix it?

**Comment by BobbyCephy** [comment]
@cambel The visual mesh but not the collision mesh of the Robotiq Hand-E is invisible in RViz under Ros Noetic. Scaled by 0.001 the visual mesh is shown in the same size as the collision mesh in RViz.

**Comment by cambel** [comment]
@BobbyCephy, I just tested `roslaunch robotiq_description display_hande.launch` (Rviz display) without changing anything on ROS noetic and it works just fine. Can you describe the scenario where it fails for you?

Screenshot from 2022-08-16 11-26-32

**Comment by BobbyCephy** [comment]
@cambel Displaying the robotiq_85_gripper with `roslaunch robotiq_description display.launch` now works fine. But the visual mesh of the robotiq_hand_e is not visible with `roslaunch robotiq_description display_hande.launch` in the current commit.

**Current visual**
current_visual

**Current collision**
current_collision

In MeshLab the size of the visual is the same as the collision mesh for the robotiq_85_gripper but 1000 times as large for the robotiq_hand_e. Scaled by 0.001 it is displayed in the same size.

**Fixed visual**
fixed_visual

**Fixed collision**
fixed_collision

**Comment by cambel** [comment]
Though I couldn't reproduce the issue, it may happen in some specific environment. 
I tested the changes on my environment and it seems to work just the same. So, I will approve this.
Thank you for your contribution!

**Comment by BobbyCephy** [comment]
That's strange. I'm using Ros Noetic under Ubuntu 20.04. Everything is up to date. Should actually be the common setup. I would have suggested as well using the version working for most people. So thank you for merging.

**Pull request merged**
